cluster1:
  labels:
    cluster: amd-1-29-blueprint
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-workloads
    targetRevision: main
    path: ./teams/team-gitops/dev/cluster1
cluster2:
  labels:
    cluster: arm-1-29-blueprint
  source:
    repoURL: https://github.com/aws-samples/eks-blueprints-workloads
    targetRevision: main
    path: ./teams/team-gitops/dev/cluster2 
spec:
  destination:
    server: https://kubernetes.default.svc
